In [7]:
import numpy as np
n = 10 # 男女の人数

In [10]:
m_prefer = np.empty([n,n])
for i in range(n):
    m_prefer[i] = np.arange(n)
    np.random.shuffle(m_prefer[i])

f_prefer = np.empty([n,n])
for i in range(n):
    f_prefer[i] = np.arange(n)
    np.random.shuffle(f_prefer[i])
"""
m_prefer[i][j]はi番目の男性のj番目の女性に対する好みの順位を表しています
f_prefer[i][j]はi番目の女性のj番目の男性に対する好みの順位を表しています

"""
    
m_engage = -np.ones(n) # 男性の婚約状態を表す -1は未婚約、それ以外はその数字の女性と婚約中ということ
f_engage = -np.ones(n) # 女性の婚約状態を表す
proposing = -1 # 婚約申し込みを保存しておく
proposed = -1 #婚約申し込まれを保存しておく

print"Men's preference is below."
print m_prefer # アルゴリズムが正しいか確認するためにとりあえず表示
print"Women's preference is below."
print f_prefer # 数字が大きいほうがより好ましい

Men's preference is below.
[[ 5.  9.  2.  0.  1.  3.  7.  4.  8.  6.]
 [ 3.  8.  4.  1.  2.  5.  9.  6.  7.  0.]
 [ 6.  0.  3.  9.  2.  7.  8.  1.  5.  4.]
 [ 6.  8.  9.  4.  3.  7.  1.  2.  0.  5.]
 [ 1.  9.  5.  2.  0.  8.  6.  7.  3.  4.]
 [ 7.  6.  0.  9.  2.  4.  1.  8.  5.  3.]
 [ 7.  3.  6.  1.  4.  5.  8.  0.  9.  2.]
 [ 2.  3.  5.  7.  8.  0.  9.  1.  4.  6.]
 [ 7.  9.  1.  4.  8.  6.  0.  2.  3.  5.]
 [ 1.  3.  5.  8.  7.  2.  6.  0.  9.  4.]]
Women's preference is below.
[[ 9.  8.  5.  3.  6.  7.  0.  4.  2.  1.]
 [ 3.  7.  0.  4.  2.  5.  9.  8.  6.  1.]
 [ 3.  9.  0.  6.  8.  4.  1.  5.  7.  2.]
 [ 0.  9.  2.  6.  4.  8.  1.  3.  5.  7.]
 [ 1.  6.  4.  9.  3.  0.  7.  5.  2.  8.]
 [ 4.  0.  8.  1.  5.  3.  7.  6.  9.  2.]
 [ 0.  1.  2.  3.  8.  6.  9.  5.  7.  4.]
 [ 4.  3.  1.  2.  0.  7.  8.  5.  6.  9.]
 [ 4.  6.  9.  5.  0.  2.  7.  3.  8.  1.]
 [ 6.  3.  0.  5.  7.  4.  2.  1.  9.  8.]]


In [11]:


while(np.sum(m_engage) != np.sum(range(n))):
    for proposing in range(n):
        if m_engage[proposing] == -1:
            proposed = np.argmin(m_prefer[proposing]) # 最も好みの相手に申し込む
            m_prefer[proposing][proposed] = n # 一度婚約申し込みをした相手には二度申し込まないようにするため
            if f_engage[proposed] == -1:
                f_engage[proposed] = proposing
                m_engage[proposing] = proposed
            else:
                if f_prefer[proposed][proposing] < f_prefer[proposed][f_engage[proposed]]:
                    m_engage[f_engage[proposed]] = -1
                    m_engage[proposing] = proposed
                    f_engage[proposed] = proposing

for i in range(n):
    print("Man " + str(i) + " got married to Woman " + str(int(m_engage[i])))
    


Man 0 got married to Woman 3
Man 1 got married to Woman 9
Man 2 got married to Woman 1
Man 3 got married to Woman 8
Man 4 got married to Woman 4
Man 5 got married to Woman 2
Man 6 got married to Woman 7
Man 7 got married to Woman 5
Man 8 got married to Woman 6
Man 9 got married to Woman 0
